language: java

jdk:
  - openjdk14

addons:
  sonarcloud:
    organization: "andreoss"
    token:
      secure: "Q7hSDr4HNtG+eKBo/+MtqQMBxdZMdDYDWaNl3rEP7wAyd5CKZ9cDLuqy+LNRbgzBcyIyR9Dgdyt9+tyY4J+RXYaJZzTGd8ToxNGLRGF5ZHN2aX0YPa4fT7IkIEdHhEd6hrasTvImQiNY8DYuX+UjXLhQoePWzSx1QwUQj8uEWpXKxhkIf8FAovUf7zANGoxtF+lb5rR+Nd96CSTKxguQFGDJJFrhgSXRRdF/85eMihT6FQM85mrVFatwJVI/NhEjDiLqwnW1mv0X/Vf1eSyKw5uBuojrkKuNQz1FD3pO5/3PSGk6vKGEMTGpAHWP2QJtZv//VBqQBpAfATjlKUoXFAxgKE57tJ7rzF9jnRdpGeKC2abWtyQQ5BwL0b07XmCjtM6A9B/ziUrE83gApUnrT4/fLLwsbT8u225IjNGgLl5ymRvIZaI3TuXvFRlmTvA+U5IQV5kohPApSApZleZard0hSCBKV0eG461iXPQZo0BFOO25AP5M3Iwqe4mEbC8RKUC6Cypvdk2mjCLwwO0nAnvR2+VVBnXbvIiHzTUVaT5CwNQjegK1CWBS2ADZQCCBfGGUSNBX2DvoxBNigkjGNriDncd5mDhyqhZuvmvUeP8k4xV8gPKBD9JE/cKgjuI2MwWuVzezmUBObjZWMgBKGr8uxeu8wL5P7PJV0tloUEg="

script:
  - ./gradlew sonarqube
